### PR TITLE
Added support for user teams

### PR DESCRIPTION
**Pull request by rick-osmo**
@jared-osmo Adds support for teams at user-level.  Also fixes that other bug from Slack.

### CODE REVIEW

**Review by jared-osmo — APPROVED** [review]
LGTM

**Comment by jared-osmo** [comment]
@rick-osmo I merged your changes and updated the local pip repository with a 1.2.2 version with your changes.  I left the 1.2.1 version as it was.

**Comment by rick-osmo** [comment]
@jared-osmo What is the best way for someone to make sure they get this jotform api and not the one on PyPI?  Is it just to pip install requirements from Osmo monorepo, or is there another pip command to just get right to it?

**Comment by jared-osmo** [comment]
@rick-osmo  I am not a pip expert, but maybe you can copy how @sam-osmo set it up, like here? https://github.com/osmoai/osmo/blob/main/build/common_requirements.txt#L3

I think that you should be able to use that --find-links line and then require jotform 1.2.1 or 1.2.2 below it I think.
Does that help?

**Comment by rick-osmo** [comment]
OK, got it, so:
```
pip install --find-links https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html jotform==1.2.1
```
should work now, and:
```
pip install --find-links https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html jotform==1.2.2
```
should work when `1.2.2` gets added to that listing?

**Comment by jared-osmo** [comment]
@rick-osmo I have not tested installing it via pip it, but I did already add 1.2.2 to the listing file.  It is on the same line, so it is kind of confusing.  I'll test installing it now.

**Comment by rick-osmo** [comment]
This is what I get for 1.2.2:
```
(python310) rick@Richards-MacBook-Pro osmo % pip install --find-links https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html jotform==1.2.2
Looking in links: https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html
ERROR: Could not find a version that satisfies the requirement jotform==1.2.2 (from versions: 1.0, 1.1, 1.2, 1.2.1)
ERROR: No matching distribution found for jotform==1.2.2
```

**Comment by jared-osmo** [comment]
@rick-osmo yeah, I am getting that too.  I'll try to see what I did wrong and fix that.  Thanks!

**Comment by jared-osmo** [comment]
@rick-osmo   I made a typo, I am fixing it now.

**Comment by jared-osmo** [comment]
@rick-osmo  It should be fixed now, but I was vexed with some caching, so you might want to wait like an hour to try again, or try a few times as sometimes I get an old version of the file when hit it.

example: 
```
(osmo) ➜  osmo git:(main) ✗ pip install --find-links https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html jotform==1.2.2

Looking in links: https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html
ERROR: Could not find a version that satisfies the requirement jotform==1.2.2 (from versions: 1.0, 1.1, 1.2, 1.2.1)
ERROR: No matching distribution found for jotform==1.2.2
```
```
(osmo) ➜  osmo git:(main) ✗ pip install --find-links https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html jotform==1.2.2

Looking in links: https://storage.googleapis.com/osmo-public-pip/pip/jotform_pip_wheel_listing.html
Collecting jotform==1.2.2
  Downloading https://storage.googleapis.com/osmo-public-pip/pip/jotform/1.2.2/jotform-1.2.2-py3-none-any.whl (12 kB)
Installing collected packages: jotform
  Attempting uninstall: jotform
    Found existing installation: jotform 1.2.1
    Uninstalling jotform-1.2.1:
      Successfully uninstalled jotform-1.2.1
Successfully installed jotform-1.2.2
```

**Comment by rick-osmo** [comment]
@jared-osmo Worked for me first try, thanks!

**Pull request merged**
